name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: '30.1'

    - uses: actions/checkout@v6
    - name: Check startup
      run: ./test-startup.sh
